// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close releases all cached database pools when the desktop application exits.
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(652368824);
}

/**
 * @param {string} id
 * @param {string} password
 * @returns {$CancellablePromise<string[]>}
 */
export function Databases(id, password) {
    return $Call.ByID(3931249150, id, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProfile(id) {
    return $Call.ByID(4275978240, id);
}

/**
 * @param {string} id
 * @param {string} password
 * @param {string} database
 * @returns {$CancellablePromise<$models.DatabaseSchema[]>}
 */
export function ExploreSchema(id, password, database) {
    return $Call.ByID(481232588, id, password, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * LocalPassword returns credentials loaded from the gitignored local connection file.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function LocalPassword(id) {
    return $Call.ByID(476022150, id);
}

/**
 * PiAssistantEvents drains events accumulated by the Pi RPC subprocess.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.PiAssistantEvent[]>}
 */
export function PiAssistantEvents(sessionID) {
    return $Call.ByID(3073914764, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionProfile[]>}
 */
export function Profiles() {
    return $Call.ByID(2084908486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @param {string} password
 * @param {string} database
 * @param {string} query
 * @returns {$CancellablePromise<$models.QueryResult>}
 */
export function RunQuery(id, password, database, query) {
    return $Call.ByID(3342371831, id, password, database, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.ConnectionProfile} profile
 * @returns {$CancellablePromise<$models.ConnectionProfile>}
 */
export function SaveProfile(profile) {
    return $Call.ByID(2940116274, profile).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SendPiAssistantPrompt submits a user message to an existing in-app Pi session.
 * @param {string} sessionID
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendPiAssistantPrompt(sessionID, message) {
    return $Call.ByID(3523061229, sessionID, message);
}

/**
 * StartPiAssistant launches Pi in RPC mode. The provided prompt context must not
 * contain credentials or SQL editor contents. Database access is separately
 * gated by the saved connection's explicit opt-in.
 * @param {string} context
 * @param {string} profileID
 * @param {string} password
 * @param {string} database
 * @returns {$CancellablePromise<string>}
 */
export function StartPiAssistant(context, profileID, password, database) {
    return $Call.ByID(1974288369, context, profileID, password, database);
}

/**
 * StopPiAssistant closes one in-app Pi RPC session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function StopPiAssistant(sessionID) {
    return $Call.ByID(4139579973, sessionID);
}

/**
 * @param {string} id
 * @param {string} password
 * @returns {$CancellablePromise<string>}
 */
export function TestConnection(id, password) {
    return $Call.ByID(3022670072, id, password);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.DatabaseSchema.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.PiAssistantEvent.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ConnectionProfile.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.QueryResult.createFrom;
