// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProfile(id) {
    return $Call.ByID(4275978240, id);
}

/**
 * LocalPassword returns credentials loaded from the gitignored local connection file.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function LocalPassword(id) {
    return $Call.ByID(476022150, id);
}

/**
 * @returns {$CancellablePromise<$models.ConnectionProfile[]>}
 */
export function Profiles() {
    return $Call.ByID(2084908486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} password
 * @param {string} query
 * @returns {$CancellablePromise<$models.QueryResult>}
 */
export function RunQuery(id, password, query) {
    return $Call.ByID(3342371831, id, password, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.ConnectionProfile} profile
 * @returns {$CancellablePromise<$models.ConnectionProfile>}
 */
export function SaveProfile(profile) {
    return $Call.ByID(2940116274, profile).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} password
 * @returns {$CancellablePromise<string>}
 */
export function TestConnection(id, password) {
    return $Call.ByID(3022670072, id, password);
}

// Private type creation functions
const $$createType0 = $models.ConnectionProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.QueryResult.createFrom;
