// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class ConnectionProfile {
    /**
     * Creates a new ConnectionProfile instance.
     * @param {Partial<ConnectionProfile>} [$$source = {}] - The source object to create the ConnectionProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("sslMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sslMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionProfile(/** @type {Partial<ConnectionProfile>} */($$parsedSource));
    }
}

export class DatabaseColumn {
    /**
     * Creates a new DatabaseColumn instance.
     * @param {Partial<DatabaseColumn>} [$$source = {}] - The source object to create the DatabaseColumn.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nullable"] = false;
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseColumn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseColumn(/** @type {Partial<DatabaseColumn>} */($$parsedSource));
    }
}

export class DatabaseObject {
    /**
     * Creates a new DatabaseObject instance.
     * @param {Partial<DatabaseObject>} [$$source = {}] - The source object to create the DatabaseObject.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {DatabaseColumn[]}
             */
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseObject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseObject}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        return new DatabaseObject(/** @type {Partial<DatabaseObject>} */($$parsedSource));
    }
}

export class DatabaseSchema {
    /**
     * Creates a new DatabaseSchema instance.
     * @param {Partial<DatabaseSchema>} [$$source = {}] - The source object to create the DatabaseSchema.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("objects" in $$source)) {
            /**
             * @member
             * @type {DatabaseObject[]}
             */
            this["objects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseSchema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseSchema}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("objects" in $$parsedSource) {
            $$parsedSource["objects"] = $$createField1_0($$parsedSource["objects"]);
        }
        return new DatabaseSchema(/** @type {Partial<DatabaseSchema>} */($$parsedSource));
    }
}

export class QueryResult {
    /**
     * Creates a new QueryResult instance.
     * @param {Partial<QueryResult>} [$$source = {}] - The source object to create the QueryResult.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {any[][]}
             */
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rowCount"] = 0;
        }
        if (!("commandTag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandTag"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult(/** @type {Partial<QueryResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DatabaseColumn.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DatabaseObject.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Array($$createType5);
